BACKPORT: scripts/dtc: Fix build error
```
/usr/bin/ld: scripts/dtc/yamltree.o: in function `dt_to_yaml':
yamltree.c:(.text+0x0): multiple definition of `dt_to_yaml'; scripts/dtc/yamltree.o:yamltree.c:(.text+0x0): first defined here
/usr/bin/ld: scripts/dtc/yamltree.o:(.data+0x0): multiple definition of `yaml_error_name'; scripts/dtc/yamltree.o:(.data+0x0): first defined here
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [scripts/Makefile.host:99: scripts/dtc/dtc] Error 1
make[1]: *** [/workspace/kernel_xiaomi_sm6225-uvite/Makefile:1384: scripts_dtc] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:153: sub-make] Error 2
```

Revert "BACKPORT: scripts/dtc: Call pkg-config POSIXly correct"
This reverts commit 63e00bad99766ad6eb990a15bc5bb33b626a6ca0.

Revert "BACKPORT: scripts/dtc: use pkg-config to include <yaml.h> in non-standard path"
This reverts commit ebe721834b8a3eb51050c5205f9af9d3da0dba82.

Revert "BACKPORT: scripts/dtc: Use pkg-config to locate libyaml"
This reverts commit 82deddff7f6cdd3ef6196001157ccf89d635eba7.

Revert "BACKPORT: scripts/dtc: Fix libyaml detection"
This reverts commit 024465f8ad96d334458525e7e61ec4e72fb22646.

Change-Id: Iaecf18ef41d79bdb6e2b00404ffd6d8980f5c673
Signed-off-by: Kajal4414 <81718060+Kajal4414@users.noreply.github.com>